import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Navigation
    home: 'Home',
    services: 'Services',
    deliveryErrands: 'Delivery & Errands',
    helpAtHome: 'Help at Home',
    pricing: 'Pricing',
    about: 'About Us',
    contact: 'Contact',
    book: 'Book Now',
    login: 'Login',
    
    // Hero
    heroTitle: 'Your Local Help in Gothenburg',
    heroSubtitle: 'Personal deliveries, errands, and everyday assistance. Trusted, reliable, and eco-conscious.',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    
    // Services
    summerServices: 'Summer Services',
    winterServices: 'Winter Services',
    summerDesc: 'Eco-conscious deliveries to leisure areas, coastal neighborhoods, lakes, and islands around Gothenburg',
    winterDesc: 'City-based home deliveries and errands within Gothenburg for a cozy, stress-free experience',
    
    // Help at Home
    petCare: 'Pet Care',
    petCareDesc: 'Short visits, feeding, and walking for your furry friends',
    dishesCleanup: 'Dishes & Cleanup',
    dishesCleanupDesc: 'Light kitchen cleanup and dish washing',
    householdHelp: 'Household Help',
    householdHelpDesc: 'Watering plants, taking out trash, light tidying',
    storePickup: 'Store Pickups',
    storePickupDesc: 'Groceries, pharmacy items, local shop errands',
    parcelReturns: 'Parcel Returns',
    parcelReturnsDesc: 'Service-point pickups and package returns',
    elderlySupport: 'Elderly Support',
    elderlySupportDesc: 'Non-medical assistance for seniors',
    
    // Booking
    bookService: 'Book a Service',
    selectService: 'Select Service Type',
    selectSeason: 'Select Season',
    summer: 'Summer',
    winter: 'Winter',
    delivery: 'Delivery',
    errand: 'Errand',
    helpAtHomeService: 'Help at Home',
    pickupAddress: 'Pickup Address',
    deliveryAddress: 'Delivery Address',
    taskLocation: 'Task Location',
    preferredDate: 'Preferred Date',
    preferredTime: 'Preferred Time',
    itemDescription: 'Item/Task Description',
    itemSize: 'Item Size',
    small: 'Small',
    medium: 'Medium',
    yourDetails: 'Your Details',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    email: 'Email',
    next: 'Next',
    previous: 'Previous',
    confirmBooking: 'Confirm Booking',
    termsAccept: 'I accept the Terms & Conditions and Privacy Policy',
    priceSummary: 'Price Summary',
    basePrice: 'Base Price',
    distanceFee: 'Distance Fee',
    addOns: 'Add-ons',
    totalPrice: 'Total Price',
    bookingConfirmed: 'Booking Confirmed!',
    bookingNumber: 'Booking Number',
    thankYou: 'Thank you for choosing TaskCham',
    
    // Pricing
    pricingTitle: 'Transparent Pricing',
    pricingSubtitle: 'No hidden fees. Know exactly what you pay.',
    startingFrom: 'Starting from',
    cityService: 'City Service',
    leisureAreas: 'Leisure Areas',
    islands: 'Islands',
    perKm: 'per km after 5km',
    waitingTime: 'Waiting Time',
    per15min: 'per 15 min',
    multipleStops: 'Multiple Stops',
    fragileItems: 'Fragile Items',
    peakTime: 'Peak Time',
    surcharge: 'surcharge',
    
    // About
    aboutTitle: 'About TaskCham',
    aboutSubtitle: 'Your trusted local service in Gothenburg',
    aboutText1: 'TaskCham was founded with a simple mission: to provide reliable, personal, and eco-conscious help to the people of Gothenburg.',
    aboutText2: 'Unlike large delivery platforms, we focus on building trust and community connections. Every task is handled with care by our vetted local drivers and helpers.',
    aboutText3: 'Based in Gothenburg, we understand the unique needs of our city – from summer escapes to the archipelago to cozy winter deliveries.',
    ourValues: 'Our Values',
    trust: 'Trust',
    trustDesc: 'Every driver and helper is carefully vetted and approved',
    local: 'Local',
    localDesc: 'Born and based in Gothenburg, serving our community',
    eco: 'Eco-Conscious',
    ecoDesc: 'Hybrid and efficient vehicles for a greener future',
    
    // Contact
    contactTitle: 'Get in Touch',
    contactSubtitle: 'We\'d love to hear from you',
    sendMessage: 'Send Message',
    yourMessage: 'Your Message',
    address: 'Address',
    
    // Driver
    becomeDriver: 'Become a Driver/Helper',
    driverSignup: 'Driver & Helper Signup',
    vehicleType: 'Vehicle Type',
    hybridCar: 'Hybrid Car',
    normalCar: 'Normal Car',
    noVehicle: 'No Vehicle (Helper)',
    serviceAreas: 'Service Areas',
    driverAgreement: 'I accept the Driver & Helper Agreement and Safety Rules',
    submitApplication: 'Submit Application',
    applicationSubmitted: 'Application Submitted!',
    pendingApproval: 'Your application is pending approval',
    
    // Driver Dashboard
    driverDashboard: 'Driver Dashboard',
    availability: 'Availability',
    available: 'Available',
    busy: 'Busy',
    offline: 'Offline',
    assignedTasks: 'Assigned Tasks',
    earnings: 'Earnings',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    totalEarnings: 'Total Earnings',
    taskDetails: 'Task Details',
    updateStatus: 'Update Status',
    pending: 'Pending',
    pickedUp: 'Picked Up',
    inProgress: 'In Progress',
    completed: 'Completed',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    overview: 'Overview',
    newBookings: 'New Bookings',
    activeBookings: 'Active Bookings',
    completedBookings: 'Completed Bookings',
    manageDrivers: 'Manage Drivers',
    managePricing: 'Manage Pricing',
    manageAreas: 'Manage Areas',
    approve: 'Approve',
    suspend: 'Suspend',
    remove: 'Remove',
    assignDriver: 'Assign Driver',
    
    // Dashboard Access
    dashboardActive: 'Active',
    dashboardDisabled: 'Temporarily Disabled',
    dashboardSuspended: 'Suspended',
    dashboardInactive: 'Your dashboard is currently inactive. Please contact TaskCham support.',
    enableAccess: 'Enable Access',
    disableAccess: 'Disable Access',
    
    // Legal
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    cancellationPolicy: 'Cancellation Policy',
    
    // Footer
    allRightsReserved: 'All rights reserved',
    madeWith: 'Made with',
    inGothenburg: 'in Gothenburg',
    
    // Common
    sek: 'SEK',
    km: 'km',
    
    // Additional Common Translations
    personalService: 'Personal Service',
    personalServiceDesc: 'We treat every task as if it were our own',
    basedOperating: 'Based & Operating',
    vettedHelpers: 'Vetted Helpers',
    ecoVehicles: 'Eco Vehicles',
    sameDayService: 'Same-Day',
    serviceAvailable: 'Service Available',
    ourStory: 'Our Story',
    storyPara1: 'TaskCham was born from a simple idea: what if getting help with everyday tasks was as easy as asking a trusted neighbor? In a world of large, impersonal delivery platforms, we saw an opportunity to do things differently.',
    storyPara2: 'Based in the heart of Gothenburg, we understand the rhythm of our city – the summer escapes to the archipelago, the cozy winter evenings when you\'d rather stay warm than venture out. We built TaskCham to serve these needs with a personal touch.',
    storyPara3: 'Every driver and helper in our network is carefully vetted and lives locally. When you book with TaskCham, you\'re not just getting a service – you\'re connecting with a member of your community who genuinely cares about doing a good job.',
    whatDrives: 'What drives everything we do',
    localAlternative: 'A Local Alternative',
    localAltDesc: 'While large platforms focus on speed and scale, we focus on trust and quality. Here\'s what sets TaskCham apart:',
    vettedApproved: 'Every helper is personally vetted and approved',
    knowGothenburg: 'We know Gothenburg inside and out',
    hybridVehicles: 'Hybrid and eco-friendly vehicles only',
    directCommunication: 'Direct communication with your helper',
    realPeople: 'Support from real people, not bots',
    fairPricing: 'Fair pricing with no hidden fees',
    joinTeam: 'Want to Join Our Team?',
    lookingForDrivers: 'We\'re always looking for reliable, friendly drivers and helpers in Gothenburg',
    
    // Home Page
    location: 'Gothenburg, Sweden',
    vettedDrivers: 'Vetted Drivers',
    ecoConscious2: 'Eco-Conscious',
    localPersonal: 'Local & Personal',
    seasonalServices: 'Seasonal Services',
    tailoredSeasons: 'Tailored to Gothenburg\'s beautiful seasons',
    summerCard: 'Summer',
    archipelagoText: 'Archipelago',
    winterCard: 'Winter',
    cityDelivery: 'City Delivery',
    nonMedicalAssistance: 'Non-medical, everyday assistance you can trust',
    whatMakesTaskCham: 'What makes TaskCham different',
    readyGetStarted: 'Ready to Get Started?',
    bookFirstDelivery: 'Book your first delivery or errand today and experience the TaskCham difference.',
    exploreAllServices: 'Explore All Services',
    
    // Delivery & Errands
    deliveryErrandsTitle: 'Delivery & Errands',
    personalReliable: 'Personal, reliable deliveries across Gothenburg — from city streets to coastal escapes',
    ecoConsciousVehicles: 'Eco-Conscious Vehicles',
    hybridFuel: 'Hybrid and fuel-efficient cars',
    flexibleScheduling: 'Flexible Scheduling',
    bookSameDay: 'Book same-day or in advance',
    allItemSizes: 'All Item Sizes',
    smallToMedium: 'Small packages to medium loads',
    realTimeUpdates: 'Real-Time Updates',
    trackDelivery: 'Track your delivery status',
    deliveryToLeisure: 'Deliveries to Leisure Areas & Archipelago',
    summerInGothenburg: 'Summer in Gothenburg means escaping to the coast. We deliver to beaches, lakes, islands, and all your favorite summer spots. Perfect for picnic supplies, forgotten items, or anything you need at your summer destination.',
    popularSummer: 'Popular Summer Destinations',
    bookSummerDelivery: 'Book Summer Delivery',
    cozyCityDeliveries: 'Cozy City Deliveries & Errands',
    coldOutside: 'When it\'s cold outside, let us handle your errands. We deliver within Gothenburg city, picking up groceries, pharmacy items, packages, and more. Stay warm while we take care of the rest.',
    cityCoverage: 'City Coverage Areas',
    bookCityDelivery: 'Book City Delivery',
    whatWeDeliver: 'What We Deliver',
    smallToMediumItems: 'Small to medium items using hybrid or regular cars',
    groceries: 'Groceries',
    fromFavorite: 'From your favorite stores',
    pharmacyItems: 'Pharmacy Items',
    medicineHealth: 'Medicine and health products',
    packages: 'Packages',
    parcelsShipments: 'Parcels and shipments',
    documents2: 'Documents',
    importantPapers: 'Important papers and files',
    foodDelivery: 'Food Delivery',
    restaurantOrders: 'Restaurant orders',
    gifts: 'Gifts',
    flowersPresents: 'Flowers, presents, surprises',
    householdItems: 'Household Items',
    essentialSupplies: 'Essential supplies',
    andMore: 'And More...',
    justAsk: 'Just ask us!',
    needDeliveryErrand: 'Need a Delivery or Errand?',
    bookGetSameDay: 'Book now and get your items delivered the same day',
    
    // Help at Home Page
    helpAtHomeTitle: 'Help at Home',
    nonMedicalEveryday: 'Non-medical, everyday assistance from trusted local helpers. We\'re here to make your life easier.',
    importantNotice: 'Important:',
    nonMedicalNotice: 'All services are non-medical and non-licensed. We do not provide healthcare, nursing, or licensed professional services.',
    ourServices: 'Our Services',
    chooseRange: 'Choose from a range of helpful services tailored to your needs',
    shortVisits: 'Short visits to check on pets',
    feedingWater: 'Feeding and water refill',
    dogWalking: 'Dog walking (short walks)',
    medicationReminder: 'Medication reminder (non-medical)',
    washingDrying: 'Washing and drying dishes',
    kitchenCounter: 'Kitchen counter cleanup',
    loadingDishwasher: 'Loading/unloading dishwasher',
    lightKitchen: 'Light kitchen organizing',
    wateringPlants: 'Watering plants',
    takingTrash: 'Taking out trash/recycling',
    lightTidying: 'Light tidying and organizing',
    mailCollection: 'Mail collection',
    groceryShopping: 'Grocery shopping',
    pharmacyPickup: 'Pharmacy pickup',
    localStoreErrands: 'Local store errands',
    dryCleaningPickup: 'Dry cleaning pickup',
    packageReturns: 'Package returns',
    postOfficeErrands: 'Post office errands',
    servicePointPickups: 'Service point pickups',
    shippingParcels: 'Shipping parcels',
    companionshipVisits: 'Companionship visits',
    helpWithErrands: 'Help with errands',
    lightHouseholdAssist: 'Light household assistance',
    technologyHelp: 'Technology help',
    whyChooseTaskCham: 'Why Choose TaskCham?',
    invitingSomeone: 'We understand that inviting someone into your home requires trust. That\'s why every helper is carefully vetted and trained to provide caring, reliable service.',
    vettedHelpersTitle: 'Vetted Helpers',
    allHelpersScreened: 'All helpers are carefully screened and approved',
    caringService: 'Caring Service',
    personalAttention: 'Personal attention and genuine care',
    flexibleHours: 'Flexible Hours',
    bookWhenSuits: 'Book when it suits you',
    whoWeHelp: 'Who We Help',
    busyProfessionals: 'Busy Professionals',
    noTimeErrands: 'No time for errands? We\'ve got you covered.',
    elderlyIndividuals: 'Elderly Individuals',
    extraHelpDaily: 'Extra help with daily tasks and companionship.',
    newParents: 'New Parents',
    focusOnBaby: 'Focus on your baby while we handle the rest.',
    anyoneNeedsHelp: 'Anyone Who Needs Help',
    recoveringTraveling: 'Recovering, traveling, or just need a hand.',
    needHelpAtHome: 'Need Help at Home?',
    bookTrustedHelper: 'Book a trusted helper today and take something off your plate',
    
    // Driver Signup
    joinTeamTrusted: 'Join our team of trusted local drivers and helpers. Make a difference in your community while earning flexible income.',
    flexibleHoursWork: 'Flexible Hours',
    workWhenSuits: 'Work when it suits you',
    fairPay: 'Fair Pay',
    competitiveRates: 'Competitive rates per task',
    joinCommunity: 'Join Community',
    bePartLocal: 'Be part of local team',
    ecoFriendly: 'Eco-Friendly',
    makePositiveImpact: 'Make a positive impact',
    yourFullName2: 'Your full name',
    reviewWithin: 'We\'ll review your application and contact you within 2-3 business days.',
    processing2: 'Processing...',
    
    // Admin Dashboard
    taskChamManagement: 'TaskCham Management',
    home3: 'Home',
    logout2: 'Logout',
    availableDrivers2: 'Available Drivers',
    bookings: 'Bookings',
    driversTab: 'Drivers',
    payoutsTab: 'Payouts',
    allBookings2: 'All Bookings',
    assignedTo2: 'Assigned to:',
    noDriverAssigned2: 'No driver assigned',
    track2: 'Track',
    chat2: 'Chat',
    pendingApproval3: 'Pending Approval',
    reject2: 'Reject',
    phone2: 'Phone:',
    vehicle: 'Vehicle:',
    areas: 'Areas:',
    none: 'None',
    disableDashboard: 'Disable Dashboard Access',
    suspendDriver2: 'Suspend Driver',
    suspend2: 'Suspend',
    temporarilyDisableAccess: 'This will temporarily disable dashboard access for',
    cannotLoginAccept: 'They won\'t be able to log in or accept tasks.',
    suspendAccount2: 'This will suspend',
    accountUntilReenabled: '\'s account. They won\'t be able to access the platform until manually re-enabled.',
    reasonOptional: 'Reason (optional)',
    enterReasonAction: 'Enter reason for this action...',
    cancel2: 'Cancel',
    confirm2: 'Confirm',
    liveTracking2: 'Live Tracking - Booking',
    driver2: 'Driver:',
    status2: 'Status:',
    liveTrackingActive2: 'Live Tracking Active',
    payoutManagement2: 'Payout Management',
    pendingPayouts2: 'Pending Payouts',
    pending2: 'Pending',
    amount2: 'Amount:',
    method2: 'Method:',
    account2: 'Account:',
    requested2: 'Requested:',
    approve2: 'Approve',
    reject3: 'Reject',
    payoutHistory2: 'Payout History',
    processing3: 'Processing',
    completed2: 'Completed',
    rejected: 'Rejected',
    processed2: 'Processed:',
    approvePayout2: 'Approve Payout',
    rejectPayout2: 'Reject Payout',
    driver3: 'Driver',
    amount3: 'Amount',
    paymentDetails2: 'Payment Details',
    processingNotesOpt: 'Processing Notes (Optional)',
    rejectionReason2: 'Rejection Reason',
    addProcessingNotes: 'Add any processing notes...',
    provideRejectionReason: 'Provide reason for rejection...',
    cancel3: 'Cancel',
    processing4: 'Processing...',
    selectAvailableDriver: 'Select an available driver for booking',
    noAvailableDriversMoment: 'No available drivers at the moment',
    tasks2: 'tasks',
    
    // Listings Page
    availableJobs: 'Available Jobs',
    showAllActive: 'Show all active customer requests and available work',
    searchTaskArea: 'Search for task, area, or store...',
    serviceType: 'Service Type',
    allServices: 'All Services',
    allStatuses: 'All Statuses',
    available2: 'Available',
    assigned2: 'Assigned',
    completed3: 'Completed',
    showing: 'Showing',
    jobs: 'jobs',
    loginFullDetails: 'Login to see full details',
    noJobsFound: 'No jobs found',
    tryChangingFilters: 'Try changing your filters or check back later',
    available3: 'Available',
    assigned3: 'Assigned',
    completed4: 'Completed',
    noDescription: 'No description',
    amountLabel: 'Amount',
    taskDetailsTitle: 'Task Details',
    serviceTypeLabel: 'Service Type',
    seasonLabel: 'Season',
    dateLabel: 'Date',
    timeLabel: 'Time',
    descriptionLabel: 'Description',
    pickupLabel: 'Pickup',
    deliveryLabel: 'Delivery',
    locationLabel: 'Location',
    customerInfo: 'Customer Information',
    nameLabel: 'Name',
    phoneLabel: 'Phone',
    loginSeeDetails: 'Login to see full details',
    contactInfoOnlyAvailable: 'Contact information and more details are only available for approved drivers and administrators.',
    loginNow: 'Login Now',
    interestedTask: 'Interested in this task?',
    contactAdminAssigned: 'Contact an administrator to be assigned this task.',
    contactSupport: 'Contact Support',
    
    // Admin Dashboard Tabs
    overviewTab: 'Overview',
    usersTab: 'Users',
    bookingsMgmtTab: 'Bookings (Advanced)',
    promoCodesTab: 'Promo Codes',
    payoutMgmtTab: 'Payouts',
    pricingTab: 'Pricing',
    performanceTab: 'Performance',
    financialTab: 'Financial',
    problemTab: 'Problems',
    cleanupTab: 'Cleanup',
    messagingTab: 'Messages',
    buyDeliverTab: 'Buy & Deliver',
    notificationsTab: 'Notifications',
    analyticsTab: 'Analytics & Reports',
    pricingAddonsTab: 'Price Add-ons',
    bookingHistoryTab: 'Booking History',
    notificationHistoryTab: 'Notification Log',
    cancellationsTab: 'Cancellations',
    priceNegotiationTab: 'Price Negotiation',
    businessAccountsTab: 'Business Accounts',
    onlineAsRunner: 'Online as Runner',
    goOnlineRunner: 'Go Online as Runner',
    allBookingsAdmin: 'All Bookings',
    unpaidBookings: 'Unpaid',
    activeBookingsFilter: 'Active',
    completedFilter: 'Completed',
    assignedToLabel: 'Assigned to',
    trackLabel: 'Track',
    chatLabel: 'Chat',
    acceptTask: 'Accept Task',
    fulfilledByTaskCham: 'Fulfilled by TaskCham',
    pendingApprovalCount: 'Pending Approval',
    requiresAttention: 'Requires attention',
    avgRating: 'avg',
    completionRate: 'completion',
    viewRatings: 'View Ratings',
    ratingsCount: 'ratings',
    openCases: 'Open Cases',
    history: 'History',
    noDisputesYet: 'No disputes yet',
    ratingsFor: 'Ratings for',
    averageRating: 'Average Rating',
    noRatingsYet: 'No ratings yet',
    allFilter: 'All',
    paid: 'Paid',
    frozen: 'Frozen',
    pendingPayment: 'Pending Payment'
  },
  sv: {
    home: 'Hem',
    services: 'Tjänster',
    deliveryErrands: 'Leverans & Ärenden',
    helpAtHome: 'Hjälp Hemma',
    pricing: 'Priser',
    about: 'Om Oss',
    contact: 'Kontakt',
    book: 'Boka Nu',
    login: 'Logga in',
    heroTitle: 'Din Lokala Hjälp i Göteborg',
    heroSubtitle: 'Personliga leveranser, ärenden och vardagshjälp. Pålitlig, trygg och miljömedveten.',
    getStarted: 'Kom Igång',
    learnMore: 'Läs Mer',
    summerServices: 'Sommartjänster',
    winterServices: 'Vintertjänster',
    summerDesc: 'Miljömedvetna leveranser till fritidsområden, kustområden, sjöar och öar runt Göteborg',
    winterDesc: 'Stadsbaserade hemleveranser och ärenden inom Göteborg för en mysig, stressfri upplevelse',
    petCare: 'Djurvård',
    petCareDesc: 'Korta besök, matning och promenader för dina husdjur',
    dishesCleanup: 'Disk & Städning',
    dishesCleanupDesc: 'Lätt köksstädning och diskning',
    householdHelp: 'Hushållshjälp',
    householdHelpDesc: 'Vattna blommor, ta ut sopor, lätt städning',
    storePickup: 'Butiksärenden',
    storePickupDesc: 'Matvaror, apoteksvaror, lokala butiksärenden',
    parcelReturns: 'Paketreturer',
    parcelReturnsDesc: 'Utlämningsställen och paketreturer',
    elderlySupport: 'Äldrestöd',
    elderlySupportDesc: 'Icke-medicinsk hjälp för äldre',
    bookService: 'Boka en Tjänst',
    selectService: 'Välj Tjänstetyp',
    selectSeason: 'Välj Säsong',
    summer: 'Sommar',
    winter: 'Vinter',
    delivery: 'Leverans',
    errand: 'Ärende',
    helpAtHomeService: 'Hjälp Hemma',
    pickupAddress: 'Upphämtningsadress',
    deliveryAddress: 'Leveransadress',
    taskLocation: 'Uppdragsplats',
    preferredDate: 'Önskat Datum',
    preferredTime: 'Önskad Tid',
    itemDescription: 'Beskrivning',
    itemSize: 'Storlek',
    small: 'Liten',
    medium: 'Medium',
    yourDetails: 'Dina Uppgifter',
    fullName: 'Fullständigt Namn',
    phoneNumber: 'Telefonnummer',
    email: 'E-post',
    next: 'Nästa',
    previous: 'Föregående',
    confirmBooking: 'Bekräfta Bokning',
    termsAccept: 'Jag accepterar Villkor och Integritetspolicy',
    priceSummary: 'Prissammanfattning',
    basePrice: 'Grundpris',
    distanceFee: 'Avståndsavgift',
    addOns: 'Tillägg',
    totalPrice: 'Totalpris',
    bookingConfirmed: 'Bokning Bekräftad!',
    bookingNumber: 'Bokningsnummer',
    thankYou: 'Tack för att du valde TaskCham',
    pricingTitle: 'Transparenta Priser',
    pricingSubtitle: 'Inga dolda avgifter. Vet exakt vad du betalar.',
    startingFrom: 'Från',
    cityService: 'Stadstjänst',
    leisureAreas: 'Fritidsområden',
    islands: 'Öar',
    perKm: 'per km efter 5km',
    waitingTime: 'Väntetid',
    per15min: 'per 15 min',
    multipleStops: 'Flera Stopp',
    fragileItems: 'Ömtåliga Varor',
    peakTime: 'Högtrafik',
    surcharge: 'tillägg',
    aboutTitle: 'Om TaskCham',
    aboutSubtitle: 'Din pålitliga lokala tjänst i Göteborg',
    aboutText1: 'TaskCham grundades med ett enkelt uppdrag: att erbjuda pålitlig, personlig och miljömedveten hjälp till Göteborgs invånare.',
    aboutText2: 'Till skillnad från stora leveransplattformar fokuserar vi på att bygga förtroende och samhällsband. Varje uppdrag hanteras med omsorg av våra godkända lokala förare och hjälpare.',
    aboutText3: 'Baserade i Göteborg förstår vi stadens unika behov – från sommarens skärgårdsutflykter till vinterns mysiga leveranser.',
    ourValues: 'Våra Värderingar',
    trust: 'Förtroende',
    trustDesc: 'Varje förare och hjälpare granskas noggrant',
    local: 'Lokal',
    localDesc: 'Född och baserad i Göteborg, tjänar vårt samhälle',
    eco: 'Miljömedveten',
    ecoDesc: 'Hybrid- och effektiva fordon för en grönare framtid',
    contactTitle: 'Kontakta Oss',
    contactSubtitle: 'Vi vill gärna höra från dig',
    sendMessage: 'Skicka Meddelande',
    yourMessage: 'Ditt Meddelande',
    address: 'Adress',
    becomeDriver: 'Bli Förare/Hjälpare',
    driverSignup: 'Förare & Hjälpare Ansökan',
    vehicleType: 'Fordonstyp',
    hybridCar: 'Hybridbil',
    normalCar: 'Vanlig Bil',
    noVehicle: 'Inget Fordon (Hjälpare)',
    serviceAreas: 'Tjänsteområden',
    driverAgreement: 'Jag accepterar Förare & Hjälpare Avtal och Säkerhetsregler',
    submitApplication: 'Skicka Ansökan',
    applicationSubmitted: 'Ansökan Inskickad!',
    pendingApproval: 'Din ansökan väntar på godkännande',
    driverDashboard: 'Förarpanel',
    availability: 'Tillgänglighet',
    available: 'Tillgänglig',
    busy: 'Upptagen',
    offline: 'Offline',
    assignedTasks: 'Tilldelade Uppdrag',
    earnings: 'Intäkter',
    thisWeek: 'Denna Vecka',
    thisMonth: 'Denna Månad',
    totalEarnings: 'Totala Intäkter',
    taskDetails: 'Uppdragsdetaljer',
    updateStatus: 'Uppdatera Status',
    pending: 'Väntande',
    pickedUp: 'Upphämtad',
    inProgress: 'Pågående',
    completed: 'Slutförd',
    adminDashboard: 'Adminpanel',
    overview: 'Översikt',
    newBookings: 'Nya Bokningar',
    activeBookings: 'Aktiva Bokningar',
    completedBookings: 'Slutförda Bokningar',
    manageDrivers: 'Hantera Förare',
    managePricing: 'Hantera Priser',
    manageAreas: 'Hantera Områden',
    approve: 'Godkänn',
    suspend: 'Avbryt',
    remove: 'Ta Bort',
    assignDriver: 'Tilldela Förare',
    dashboardActive: 'Aktiv',
    dashboardDisabled: 'Tillfälligt Inaktiverad',
    dashboardSuspended: 'Avstängd',
    dashboardInactive: 'Din panel är för närvarande inaktiv. Kontakta TaskCham support.',
    enableAccess: 'Aktivera Åtkomst',
    disableAccess: 'Inaktivera Åtkomst',
    privacyPolicy: 'Integritetspolicy',
    termsConditions: 'Allmänna Villkor',
    cancellationPolicy: 'Avbokningspolicy',
    allRightsReserved: 'Alla rättigheter förbehållna',
    madeWith: 'Gjord med',
    inGothenburg: 'i Göteborg',
    sek: 'SEK',
    km: 'km',

    // Additional translations for hardcoded text
    whatNeedHelp: 'Vad behöver du hjälp med?',
    locationTime: 'Plats & Tid',
    whereWhen: 'Var och när behöver du oss?',
    howContact: 'Hur kan vi kontakta dig?',
    reviewDetails: 'Granska dina bokningsdetaljer',
    service: 'Tjänst',
    season: 'Säsong',
    pickup: 'Upphämtning',
    deliveryDest: 'Leverans',
    location: 'Plats',
    dateTime: 'Datum & Tid',
    sendingConfirmation: 'Vi har skickat en bekräftelse till',
    backToHome: 'Tillbaka till Hem',
    processing: 'Bearbetar...',
    cancel: 'Avbryt',
    taskDescription: 'Uppgiftsbeskrivning',
    selectServiceType: 'Välj servicetyp',
    enterPickupAddress: 'Ange upphämtningsadress i Göteborg',
    enterDeliveryAddress: 'Ange leveransadress',
    enterYourAddress: 'Ange din adress',
    describeItems: 'Beskriv vad du behöver hjälp med...',
    describeTask: 'Beskriv vad du behöver levererat eller upphämtat...',
    yourFullName: 'Ditt fullständiga namn',
    setDueDate: 'Välj datum',
    minimum100: 'Minimum 100 SEK',

    // Dashboard translations
    myTasks: 'Mina Uppdrag',
    payoutsEarnings: 'Utbetalningar & Intäkter',
    activeTasks: 'Aktiva Uppdrag',
    noActiveTasks: 'Inga aktiva uppdrag tilldelade till dig',
    recentlyCompleted: 'Nyligen Slutförda',
    viewMap: 'Visa Karta',
    chat: 'Chatt',
    markPickedUp: 'Markera som Upphämtad',
    startDelivery: 'Starta Leverans',
    complete: 'Slutför',
    liveTracking: 'Live-spårning',
    startTracking: 'Starta Spårning',
    stopTracking: 'Stoppa Spårning',
    active: 'Aktiv',
    yourLocation: 'Din plats delas med kund och admin',
    stopWhenComplete: 'Stoppa spårning när uppdraget är slutfört',
    lastUpdated: 'Senast uppdaterad',
    position: 'Position',

    // Payout translations
    currentBalance: 'Aktuellt Saldo',
    requestPayout: 'Begär Utbetalning',
    thisWeekShort: 'Denna Vecka',
    thisMonthShort: 'Denna Månad',
    completedTasks: 'Slutförda Uppdrag',
    payoutHistory: 'Utbetalningshistorik',
    earningsHistory: 'Intäktshistorik',
    noCompletedTasks: 'Inga slutförda uppdrag än',
    noPayoutRequests: 'Inga utbetalningsbegäranden än',
    payoutStatus: 'Status',
    payoutPending: 'Väntande',
    payoutProcessing: 'Bearbetas',
    payoutCompleted: 'Slutförd',
    payoutRejected: 'Avvisad',
    requested: 'Begärd',
    method: 'Metod',
    processed: 'Bearbetad',
    availableBalance: 'Tillgängligt Saldo',
    payoutAmount: 'Utbetalningsbelopp',
    minimumPayout: 'Minimum utbetalning: 100 SEK',
    paymentMethod: 'Betalningsmetod',
    bankTransfer: 'Banköverföring',
    swish: 'Swish',
    bankAccount: 'Bankkonto',
    swishNumber: 'Swish-nummer',
    requestingPayout: 'Begär utbetalning...',

    // Admin translations
    allBookings: 'Alla Bokningar',
    drivers: 'Förare',
    payouts: 'Utbetalningar',
    availableDrivers: 'Tillgängliga Förare',
    pendingApprovalDrivers: 'Väntande Godkännande',
    noDriversAvailable: 'Inga tillgängliga förare för tillfället',
    selectDriver: 'Välj en tillgänglig förare för bokning',
    tasks: 'uppdrag',
    disableDashboardAccess: 'Inaktivera Panelåtkomst',
    suspendDriver: 'Stäng av Förare',
    temporarilyDisable: 'Detta kommer tillfälligt inaktivera panelåtkomsten för',
    cannotLogin: 'De kommer inte kunna logga in eller acceptera uppdrag.',
    suspendAccount: 'Detta kommer att stänga av',
    cannotAccess: 's konto. De kommer inte kunna komma åt plattformen förrän manuellt återaktiverad.',
    reason: 'Anledning (valfritt)',
    enterReason: 'Ange anledning för denna åtgärd...',
    confirm: 'Bekräfta',
    reject: 'Avvisa',
    payoutManagement: 'Utbetalningshantering',
    pendingPayouts: 'Väntande Utbetalningar',
    amount: 'Belopp',
    account: 'Konto',
    approvePayout: 'Godkänn Utbetalning',
    rejectPayout: 'Avvisa Utbetalning',
    driver: 'Förare',
    paymentDetails: 'Betalningsdetaljer',
    processingNotes: 'Bearbetningsanteckningar (Valfritt)',
    rejectionReason: 'Anledning för avvisning',
    addNotes: 'Lägg till bearbetningsanteckningar...',
    provideReason: 'Ange anledning för avvisning...',
    approving: 'Godkänner...',
    rejecting: 'Avvisar...',

    // Other common translations
    home2: 'Hem',
    logout: 'Logga ut',
    dashboardInactiveMsg: 'Panel Inaktiv',
    noDriverProfile: 'Ingen Förarprofi Hittad',
    needToApply: 'Du måste ansöka som förare/hjälpare först.',
    applyNow: 'Ansök Nu',
    applicationPending: 'Ansökan Väntande',
    accountSuspended: 'Konto Avstängt',
    applicationReview: 'Din ansökan granskas. Vi meddelar dig när den är godkänd.',
    accountSuspendedMsg: 'Ditt konto har stängts av. Kontakta support.',
    loadingMessages: 'Laddar meddelanden...',
    noMessagesYet: 'Inga meddelanden än',
    startConversation: 'Starta konversationen',
    typeMessage: 'Skriv ett meddelande...',
    customer: 'kund',
    admin: 'admin',
    adminSupportChat: 'Admin Supportchatt',
    taskSupportChat: 'Uppdragssupportchatt',
    liveTrackingActive: 'Live-spårning Aktiv',
    destination: 'Destination',
    pickupLocation: 'Upphämtningsplats',
    deliveryLocation: 'Leveransplats',
    serviceLocation: 'Serviceplats',
    driverLocation: 'Förarplats',
    track: 'Spåra',
    noDriverAssigned: 'Ingen förare tilldelad',
    assignedTo: 'Tilldelad till',
    updatedColon: 'Uppdaterad:',
    enterPassword: 'Ange lösenord',
    forgotPassword: 'Glömt lösenord?',
    loginButton: 'Logga in',
    dontHaveAccount: 'Har du inget konto?',
    signUp: 'Registrera dig',
    
    // Profile & Documents
    profile: 'Profil',
    myProfile: 'Min Profil',
    personalInfo: 'Personlig Information',
    vehicleInfo: 'Fordonsinformation',
    documents: 'Dokument',
    paymentInfo: 'Betalningsinformation',
    accountOverview: 'Kontoöversikt',
    memberSince: 'Medlem sedan',
    noVehicleRegistered: 'Inget fordon registrerat (Hjälpare)',
    registrationNumber: 'Registreringsnummer',
    makeModel: 'Märke & Modell',
    year: 'Årsmodell',
    color: 'Färg',
    insuranceInfo: 'Försäkringsinformation',
    insuranceCompany: 'Försäkringsbolag',
    policyNumber: 'Försäkringsnummer',
    expiryDate: 'Utgångsdatum',
    expiringSoon: 'Går ut snart',
    expired: 'Utgången!',
    licenseInfo: 'Körkortsinformation',
    licenseNumber: 'Körkortnummer',
    saveChanges: 'Spara ändringar',
    saving: 'Sparar...',
    documentsCertificates: 'Dokument & Certifikat',
    driversLicense: 'Körkort',
    uploadLicense: 'Ladda upp bild på ditt körkort',
    uploaded: 'Uppladdat',
    viewDocument: 'Visa dokument',
    uploadNew: 'Ladda upp nytt',
    clickToUpload: 'Klicka för att ladda upp',
    insuranceCert: 'Försäkringsbevis',
    uploadInsurance: 'Ladda upp fordonets försäkringsbevis',
    registrationCert: 'Registreringsbevis',
    uploadRegistration: 'Ladda upp fordonets registreringsbevis',
    uploadingDocument: 'Laddar upp dokument...',
    paymentInfoNote: 'Denna information används för att betala ut dina intäkter. Se till att uppgifterna är korrekta.',
    clearingAccount: 'Bankkonto (Clearing-Kontonummer)',
    accountFormat: 'Format: Clearingnummer-Kontonummer (ex: 1234-1234567)',
    swishFormat: 'Ange ditt mobilnummer kopplat till Swish',
    profileUpdated: 'Profil uppdaterad!',
    couldNotUpdate: 'Kunde inte uppdatera profil',
    documentUploaded: 'Dokument uppladdat!',
    couldNotUpload: 'Kunde inte ladda upp dokument',
    
    // Pricing page
    withinCity: 'Inom Göteborg',
    coastalLake: 'Kust- & Sjöområden',
    archipelago: 'Skärgårdsdestinationer',
    upTo5km: 'Upp till 5 km inkluderat',
    sameDayDelivery: 'Leverans samma dag tillgänglig',
    realTimeTracking: 'Realtidsspårning',
    beaches: 'Stränder, sjöar & naturområden',
    extendedZone: 'Utökad leveranszon',
    ecoTransport: 'Miljömedveten transport',
    mostPopular: 'Mest Populär',
    marstrand: 'Marstrand, Vrångö & mer',
    ferryCoord: 'Färjekoordinering',
    islandPricing: 'Öspecifik prissättning',
    perStop: 'per stopp',
    perOrder: 'per beställning',
    distancePricing: 'Avståndsprissättning',
    additionalDistance: 'Extra Avståndsavgift',
    first5km: 'Första 5 km inkluderat i grundpris',
    optionalAddons: 'Valfria Tillägg',
    additionalServices: 'Extra tjänster du kan lägga till din bokning',
    helpAtHomePricing: 'Hjälp Hemma Priser',
    nonMedical: 'Icke-medicinsk hushållshjälp',
    petCareShort: 'Djurvård (kort besök)',
    dishesKitchen: 'Disk & Köksstädning',
    lightHousehold: 'Lätt Hushållshjälp',
    storePickupErr: 'Butiksupphämtning / Ärenden',
    parcelRet: 'Paketreturer',
    elderlyHour: 'Äldrestöd (1 timme)',
    howPricingWorks: 'Hur Prissättningen Fungerar',
    priceExplanation: 'Alla priser är startpriser. Slutligt pris beräknas baserat på avstånd, servicetyp och eventuella tillägg du väljer. Du ser alltid totalpriset innan du bekräftar bokningen – inga överraskningar.',
    readyToBook: 'Redo att Boka?',
    instantQuote: 'Få en omedelbar prisuppgift när du bokar',
    
    // Contact page
    getInTouch: 'Kontakta Oss',
    hours: 'Öppettider',
    monFri: 'Mån-Fre: 8:00-20:00\nLör-Sön: 9:00-18:00',
    gothenburgSweden: 'Göteborg, Sverige',
    messageSent: 'Meddelande Skickat!',
    thankYouMessage: 'Tack för att du hörde av dig. Vi återkommer inom 24 timmar.',
    subject: 'Ämne',
    sending: 'Skickar...',
    
    // Booking page
    whatKindHelp: 'Vilken typ av hjälp behöver du?',
    packageDelivery: 'Paket och varor leverans',
    shoppingPickups: 'Shopping och upphämtningar',
    homeAssistance: 'Hemhjälpstjänster',
    selectServiceHelp: 'Välj Tjänst',
    taskDetails2: 'Uppdragsdetaljer',
    optional: 'Valfritt',
    terms: 'Villkor',
    privacy: 'Integritetspolicy',
    weveSent: 'Vi har skickat en bekräftelse till',
    
    // Footer
    trustedLocal: 'Din pålitliga lokala tjänst i Göteborg. Personliga leveranser, ärenden och vardagshjälp.',
    company: 'Företag',
    legal: 'Juridiskt',
    
    // Driver dashboard
    activeTasks2: 'Aktiva Uppdrag',
    noActiveAssigned: 'Inga aktiva uppdrag tilldelade till dig',
    recentComplete: 'Nyligen Slutförda',
    markAsPickedUp: 'Markera som Upphämtad',
    startDeliv: 'Starta Leverans',
    completeTask: 'Slutför',
    
    // Admin
    availDrivers: 'Tillgängliga Förare',
    pendingApproval2: 'Väntande Godkännande',
    noAvailableDrivers: 'Inga tillgängliga förare för tillfället',
    selectAvailable: 'Välj en tillgänglig förare för bokning',
    
    // Ytterligare Gemensamma Översättningar
    personalService: 'Personlig Service',
    personalServiceDesc: 'Vi behandlar varje uppdrag som om det vore vårt eget',
    basedOperating: 'Baserad & Verksam',
    vettedHelpers: 'Granskade Hjälpare',
    ecoVehicles: 'Miljöfordon',
    sameDayService: 'Samma Dag',
    serviceAvailable: 'Service Tillgänglig',
    ourStory: 'Vår Historia',
    storyPara1: 'TaskCham föddes ur en enkel idé: tänk om det att få hjälp med vardagssysslor var lika enkelt som att fråga en betrodd granne? I en värld av stora, opersonliga leveransplattformar såg vi en möjlighet att göra saker annorlunda.',
    storyPara2: 'Baserade i hjärtat av Göteborg förstår vi stadens rytm – sommarens flykt till skärgården, de mysiga vinterkvällarna när man hellre vill hålla sig varm än ge sig ut. Vi byggde TaskCham för att tjäna dessa behov med en personlig touch.',
    storyPara3: 'Varje förare och hjälpare i vårt nätverk är noggrant granskad och bor lokalt. När du bokar med TaskCham får du inte bara en tjänst – du kopplar samman med en medlem av ditt samhälle som verkligen bryr sig om att göra ett bra jobb.',
    whatDrives: 'Vad som driver allt vi gör',
    localAlternative: 'Ett Lokalt Alternativ',
    localAltDesc: 'Medan stora plattformar fokuserar på hastighet och skala, fokuserar vi på förtroende och kvalitet. Här är vad som skiljer TaskCham:',
    vettedApproved: 'Varje hjälpare är personligt granskad och godkänd',
    knowGothenburg: 'Vi känner Göteborg in och ut',
    hybridVehicles: 'Endast hybrid- och miljövänliga fordon',
    directCommunication: 'Direkt kommunikation med din hjälpare',
    realPeople: 'Support från riktiga människor, inte botar',
    fairPricing: 'Rättvis prissättning utan dolda avgifter',
    joinTeam: 'Vill du Gå Med i Vårt Team?',
    lookingForDrivers: 'Vi söker alltid pålitliga, vänliga förare och hjälpare i Göteborg',
    
    // Hemsida
    location: 'Göteborg, Sverige',
    vettedDrivers: 'Granskade Förare',
    ecoConscious2: 'Miljömedveten',
    localPersonal: 'Lokal & Personlig',
    seasonalServices: 'Säsongstjänster',
    tailoredSeasons: 'Anpassade till Göteborgs vackra årstider',
    summerCard: 'Sommar',
    archipelagoText: 'Skärgård',
    winterCard: 'Vinter',
    cityDelivery: 'Stadsleverans',
    nonMedicalAssistance: 'Icke-medicinsk, vardagshjälp du kan lita på',
    whatMakesTaskCham: 'Vad som gör TaskCham annorlunda',
    readyGetStarted: 'Redo att Komma Igång?',
    bookFirstDelivery: 'Boka din första leverans eller ärende idag och upplev TaskCham-skillnaden.',
    exploreAllServices: 'Utforska Alla Tjänster',
    
    // Leverans & Ärenden
    deliveryErrandsTitle: 'Leverans & Ärenden',
    personalReliable: 'Personliga, pålitliga leveranser över hela Göteborg — från stadsgator till kustflykt',
    ecoConsciousVehicles: 'Miljömedvetna Fordon',
    hybridFuel: 'Hybrid- och bränslesnåla bilar',
    flexibleScheduling: 'Flexibel Schemaläggning',
    bookSameDay: 'Boka samma dag eller i förväg',
    allItemSizes: 'Alla Artikelstorlekar',
    smallToMedium: 'Små paket till medelstora laster',
    realTimeUpdates: 'Realtidsuppdateringar',
    trackDelivery: 'Spåra din leveransstatus',
    deliveryToLeisure: 'Leveranser till Fritidsområden & Skärgård',
    summerInGothenburg: 'Sommaren i Göteborg betyder flykt till kusten. Vi levererar till stränder, sjöar, öar och alla dina favoritsommarställen. Perfekt för picknicktillbehör, glömda saker eller vad du än behöver på din sommardestination.',
    popularSummer: 'Populära Sommardestinationer',
    bookSummerDelivery: 'Boka Sommarleverans',
    cozyCityDeliveries: 'Mysiga Stadsleveranser & Ärenden',
    coldOutside: 'När det är kallt ute låter vi hantera dina ärenden. Vi levererar inom Göteborg, hämtar matvaror, apoteksvaror, paket med mera. Håll dig varm medan vi tar hand om resten.',
    cityCoverage: 'Stadens Täckningsområden',
    bookCityDelivery: 'Boka Stadsleverans',
    whatWeDeliver: 'Vad Vi Levererar',
    smallToMediumItems: 'Små till medelstora varor med hybrid- eller vanliga bilar',
    groceries: 'Matvaror',
    fromFavorite: 'Från dina favoritbutiker',
    pharmacyItems: 'Apoteksvaror',
    medicineHealth: 'Medicin och hälsoprodukter',
    packages: 'Paket',
    parcelsShipments: 'Paket och försändelser',
    documents2: 'Dokument',
    importantPapers: 'Viktiga papper och filer',
    foodDelivery: 'Matleverans',
    restaurantOrders: 'Restaurangbeställningar',
    gifts: 'Presenter',
    flowersPresents: 'Blommor, presenter, överraskningar',
    householdItems: 'Hushållsartiklar',
    essentialSupplies: 'Viktiga förnödenheter',
    andMore: 'Och Mer...',
    justAsk: 'Fråga oss bara!',
    needDeliveryErrand: 'Behöver du en Leverans eller Ärende?',
    bookGetSameDay: 'Boka nu och få dina varor levererade samma dag',
    
    // Hjälp Hemma Sida
    helpAtHomeTitle: 'Hjälp Hemma',
    nonMedicalEveryday: 'Icke-medicinsk, vardagshjälp från betrodda lokala hjälpare. Vi är här för att göra ditt liv enklare.',
    importantNotice: 'Viktigt:',
    nonMedicalNotice: 'Alla tjänster är icke-medicinska och icke-licensierade. Vi tillhandahåller inte sjukvård, omvårdnad eller licensierade professionella tjänster.',
    ourServices: 'Våra Tjänster',
    chooseRange: 'Välj bland en rad hjälpsamma tjänster anpassade till dina behov',
    shortVisits: 'Korta besök för att kolla på husdjur',
    feedingWater: 'Matning och vattenpåfyllning',
    dogWalking: 'Hundpromenader (korta promenader)',
    medicationReminder: 'Medicinpåminnelse (icke-medicinsk)',
    washingDrying: 'Tvätta och torka disk',
    kitchenCounter: 'Köksbänkstädning',
    loadingDishwasher: 'Lasta/tömma diskmaskin',
    lightKitchen: 'Lätt köksorganisering',
    wateringPlants: 'Vattna växter',
    takingTrash: 'Ta ut sopor/återvinning',
    lightTidying: 'Lätt städning och organisering',
    mailCollection: 'Postinhämtning',
    groceryShopping: 'Matvaruinköp',
    pharmacyPickup: 'Apoteksupphämtning',
    localStoreErrands: 'Lokala butiksärenden',
    dryCleaningPickup: 'Kemtvättsupphämtning',
    packageReturns: 'Paketreturer',
    postOfficeErrands: 'Postkontorärender',
    servicePointPickups: 'Utlämningsställen',
    shippingParcels: 'Skicka paket',
    companionshipVisits: 'Sällskapsbesök',
    helpWithErrands: 'Hjälp med ärenden',
    lightHouseholdAssist: 'Lätt hushållshjälp',
    technologyHelp: 'Teknikhjälp',
    whyChooseTaskCham: 'Varför Välja TaskCham?',
    invitingSomeone: 'Vi förstår att bjuda in någon i ditt hem kräver förtroende. Därför är varje hjälpare noggrant granskad och utbildad för att ge omtänksam, pålitlig service.',
    vettedHelpersTitle: 'Granskade Hjälpare',
    allHelpersScreened: 'Alla hjälpare är noggrant granskade och godkända',
    caringService: 'Omtänksam Service',
    personalAttention: 'Personlig uppmärksamhet och genuint omsorg',
    flexibleHours: 'Flexibla Tider',
    bookWhenSuits: 'Boka när det passar dig',
    whoWeHelp: 'Vem Vi Hjälper',
    busyProfessionals: 'Upptagna Yrkesverksamma',
    noTimeErrands: 'Ingen tid för ärenden? Vi har dig täckt.',
    elderlyIndividuals: 'Äldre Individer',
    extraHelpDaily: 'Extra hjälp med dagliga uppgifter och sällskap.',
    newParents: 'Nya Föräldrar',
    focusOnBaby: 'Fokusera på din bebis medan vi hanterar resten.',
    anyoneNeedsHelp: 'Alla Som Behöver Hjälp',
    recoveringTraveling: 'Återhämtar dig, reser eller bara behöver en hjälpande hand.',
    needHelpAtHome: 'Behöver du Hjälp Hemma?',
    bookTrustedHelper: 'Boka en betrodd hjälpare idag och ta något från din tallrik',
    
    // Föraransökan
    joinTeamTrusted: 'Gå med i vårt team av betrodda lokala förare och hjälpare. Gör skillnad i ditt samhälle samtidigt som du tjänar flexibel inkomst.',
    flexibleHoursWork: 'Flexibla Timmar',
    workWhenSuits: 'Arbeta när det passar dig',
    fairPay: 'Rättvis Betalning',
    competitiveRates: 'Konkurrenskraftiga priser per uppdrag',
    joinCommunity: 'Gå Med i Samhället',
    bePartLocal: 'Var en del av lokalt team',
    ecoFriendly: 'Miljövänlig',
    makePositiveImpact: 'Gör en positiv påverkan',
    yourFullName2: 'Ditt fullständiga namn',
    reviewWithin: 'Vi granskar din ansökan och kontaktar dig inom 2-3 arbetsdagar.',
    processing2: 'Bearbetar...',
    
    // Adminpanel
    taskChamManagement: 'TaskCham Hantering',
    home3: 'Hem',
    logout2: 'Logga ut',
    availableDrivers2: 'Tillgängliga Förare',
    bookings: 'Bokningar',
    driversTab: 'Förare',
    payoutsTab: 'Utbetalningar',
    allBookings2: 'Alla Bokningar',
    assignedTo2: 'Tilldelad till:',
    noDriverAssigned2: 'Ingen förare tilldelad',
    track2: 'Spåra',
    chat2: 'Chatt',
    pendingApproval3: 'Väntande Godkännande',
    reject2: 'Avvisa',
    phone2: 'Telefon:',
    vehicle: 'Fordon:',
    areas: 'Områden:',
    none: 'Ingen',
    disableDashboard: 'Inaktivera Panelåtkomst',
    suspendDriver2: 'Stäng av Förare',
    suspend2: 'Stäng av',
    temporarilyDisableAccess: 'Detta kommer tillfälligt inaktivera panelåtkomsten för',
    cannotLoginAccept: 'De kommer inte kunna logga in eller acceptera uppdrag.',
    suspendAccount2: 'Detta kommer att stänga av',
    accountUntilReenabled: 's konto. De kommer inte kunna komma åt plattformen förrän manuellt återaktiverad.',
    reasonOptional: 'Anledning (valfritt)',
    enterReasonAction: 'Ange anledning för denna åtgärd...',
    cancel2: 'Avbryt',
    confirm2: 'Bekräfta',
    liveTracking2: 'Live-spårning - Bokning',
    driver2: 'Förare:',
    status2: 'Status:',
    liveTrackingActive2: 'Live-spårning Aktiv',
    payoutManagement2: 'Utbetalningshantering',
    pendingPayouts2: 'Väntande Utbetalningar',
    pending2: 'Väntande',
    amount2: 'Belopp:',
    method2: 'Metod:',
    account2: 'Konto:',
    requested2: 'Begärd:',
    approve2: 'Godkänn',
    reject3: 'Avvisa',
    payoutHistory2: 'Utbetalningshistorik',
    processing3: 'Bearbetas',
    completed2: 'Slutförd',
    rejected: 'Avvisad',
    processed2: 'Bearbetad:',
    approvePayout2: 'Godkänn Utbetalning',
    rejectPayout2: 'Avvisa Utbetalning',
    driver3: 'Förare',
    amount3: 'Belopp',
    paymentDetails2: 'Betalningsdetaljer',
    processingNotesOpt: 'Bearbetningsanteckningar (Valfritt)',
    rejectionReason2: 'Anledning för Avvisning',
    addProcessingNotes: 'Lägg till bearbetningsanteckningar...',
    provideRejectionReason: 'Ange anledning för avvisning...',
    cancel3: 'Avbryt',
    processing4: 'Bearbetar...',
    selectAvailableDriver: 'Välj en tillgänglig förare för bokning',
    noAvailableDriversMoment: 'Inga tillgängliga förare för tillfället',
    tasks2: 'uppdrag',
    
    // Admin Dashboard Tabs
    overviewTab: 'Översikt',
    usersTab: 'Användare',
    bookingsMgmtTab: 'Bokningar (Avancerat)',
    promoCodesTab: 'Kampanjkoder',
    payoutMgmtTab: 'Utbetalningar',
    pricingTab: 'Prissättning',
    performanceTab: 'Prestanda',
    financialTab: 'Ekonomi',
    problemTab: 'Problem',
    cleanupTab: 'Cleanup',
    messagingTab: 'Meddelanden',
    buyDeliverTab: 'Köp & Leverera',
    notificationsTab: 'Notiser',
    analyticsTab: 'Analytics & Rapporter',
    pricingAddonsTab: 'Pristillägg',
    bookingHistoryTab: 'Bokningshistorik',
    notificationHistoryTab: 'Notiseringslogg',
    cancellationsTab: 'Avbokningar',
    priceNegotiationTab: 'Prisförhandling',
    businessAccountsTab: 'Företagskonton',
    onlineAsRunner: 'Online som Runner',
    goOnlineRunner: 'Gå Online som Runner',
    allBookingsAdmin: 'Alla Bokningar',
    unpaidBookings: 'Ej Betalda',
    activeBookingsFilter: 'Aktiva',
    completedFilter: 'Slutförda',
    assignedToLabel: 'Tilldelad till',
    trackLabel: 'Spåra',
    chatLabel: 'Chatt',
    acceptTask: 'Acceptera Uppdrag',
    fulfilledByTaskCham: 'Utförd av TaskCham',
    pendingApprovalCount: 'Väntande Godkännande',
    requiresAttention: 'Kräver uppmärksamhet',
    avgRating: 'avg',
    completionRate: 'slutförd',
    viewRatings: 'Visa Betyg',
    ratingsCount: 'betyg',
    openCases: 'Öppna Ärenden',
    history: 'Historik',
    noDisputesYet: 'Inga problemrapporter',
    ratingsFor: 'Betyg för',
    averageRating: 'Genomsnittligt Betyg',
    noRatingsYet: 'Inga betyg än',
    allFilter: 'Alla',
    paid: 'Betald',
    frozen: 'Frusen',
    pendingPayment: 'Väntande Betalning',
    
    // Uppdragssida
    availableJobs: 'Tillgängliga Uppdrag',
    showAllActive: 'Visa alla aktiva kundförfrågningar och tillgängligt arbete',
    searchTaskArea: 'Sök efter uppgift, område eller butik...',
    serviceType: 'Tjänstetyp',
    allServices: 'Alla Tjänster',
    allStatuses: 'Alla Statusar',
    available2: 'Tillgängliga',
    assigned2: 'Tilldelade',
    completed3: 'Slutförda',
    showing: 'Visar',
    jobs: 'uppdrag',
    loginFullDetails: 'Logga in för att se fullständiga detaljer',
    noJobsFound: 'Inga uppdrag hittades',
    tryChangingFilters: 'Prova att ändra dina sökfilter eller kom tillbaka senare',
    available3: 'Tillgänglig',
    assigned3: 'Tilldelad',
    completed4: 'Slutförd',
    noDescription: 'Ingen beskrivning',
    amountLabel: 'Belopp',
    taskDetailsTitle: 'Uppdragsdetaljer',
    serviceTypeLabel: 'Tjänstetyp',
    seasonLabel: 'Säsong',
    dateLabel: 'Datum',
    timeLabel: 'Tid',
    descriptionLabel: 'Beskrivning',
    pickupLabel: 'Upphämtning',
    deliveryLabel: 'Leverans',
    locationLabel: 'Plats',
    customerInfo: 'Kundinformation',
    nameLabel: 'Namn',
    phoneLabel: 'Telefon',
    loginSeeDetails: 'Logga in för att se fullständiga detaljer',
    contactInfoOnlyAvailable: 'Kontaktinformation och fler detaljer är endast tillgängliga för godkända förare och administratörer.',
    loginNow: 'Logga in Nu',
    interestedTask: 'Intresserad av detta uppdrag?',
    contactAdminAssigned: 'Kontakta en administratör för att tilldelas detta uppdrag.',
    contactSupport: 'Kontakta Support',
  },
  ar: {
    home: 'الرئيسية',
    services: 'الخدمات',
    deliveryErrands: 'التوصيل والمهام',
    helpAtHome: 'المساعدة المنزلية',
    pricing: 'الأسعار',
    about: 'من نحن',
    contact: 'اتصل بنا',
    book: 'احجز الآن',
    login: 'تسجيل الدخول',
    heroTitle: 'مساعدتك المحلية في غوتنبرغ',
    heroSubtitle: 'توصيل شخصي ومهام ومساعدة يومية. موثوق وآمن وصديق للبيئة.',
    getStarted: 'ابدأ الآن',
    learnMore: 'اعرف المزيد',
    summerServices: 'خدمات الصيف',
    winterServices: 'خدمات الشتاء',
    petCare: 'رعاية الحيوانات',
    petCareDesc: 'زيارات قصيرة وتغذية ومشي للحيوانات الأليفة',
    bookService: 'احجز خدمة',
    selectService: 'اختر نوع الخدمة',
    delivery: 'توصيل',
    errand: 'مهمة',
    next: 'التالي',
    previous: 'السابق',
    confirmBooking: 'تأكيد الحجز',
    sek: 'كرونة',
    km: 'كم'
  },
  fr: {
    home: 'Accueil',
    services: 'Services',
    deliveryErrands: 'Livraison & Courses',
    helpAtHome: 'Aide à Domicile',
    pricing: 'Tarifs',
    about: 'À Propos',
    contact: 'Contact',
    book: 'Réserver',
    login: 'Connexion',
    heroTitle: 'Votre Aide Locale à Göteborg',
    heroSubtitle: 'Livraisons personnelles, courses et assistance quotidienne. Fiable et écologique.',
    getStarted: 'Commencer',
    learnMore: 'En Savoir Plus',
    bookService: 'Réserver un Service',
    next: 'Suivant',
    previous: 'Précédent',
    sek: 'SEK',
    km: 'km'
  },
  sw: {
    home: 'Nyumbani',
    services: 'Huduma',
    deliveryErrands: 'Utoaji & Makazi',
    helpAtHome: 'Msaada Nyumbani',
    pricing: 'Bei',
    about: 'Kuhusu Sisi',
    contact: 'Wasiliana',
    book: 'Weka Nafasi',
    heroTitle: 'Msaada Wako wa Mtaa Göteborg',
    getStarted: 'Anza',
    next: 'Ifuatayo',
    sek: 'SEK',
    km: 'km'
  },
  da: {
    home: 'Hjem',
    services: 'Tjenester',
    deliveryErrands: 'Levering & Ærinder',
    helpAtHome: 'Hjælp Hjemme',
    pricing: 'Priser',
    about: 'Om Os',
    contact: 'Kontakt',
    book: 'Book Nu',
    heroTitle: 'Din Lokale Hjælp i Göteborg',
    heroSubtitle: 'Personlige leverancer, ærinder og daglig hjælp. Pålidelig og miljøbevidst.',
    getStarted: 'Kom i Gang',
    next: 'Næste',
    sek: 'SEK',
    km: 'km'
  },
  es: {
    home: 'Inicio',
    services: 'Servicios',
    deliveryErrands: 'Entregas y Recados',
    helpAtHome: 'Ayuda en Casa',
    pricing: 'Precios',
    about: 'Nosotros',
    contact: 'Contacto',
    book: 'Reservar',
    heroTitle: 'Tu Ayuda Local en Gotemburgo',
    heroSubtitle: 'Entregas personales, recados y asistencia diaria. Confiable y ecológico.',
    getStarted: 'Empezar',
    next: 'Siguiente',
    sek: 'SEK',
    km: 'km'
  },
  so: {
    home: 'Hoyga',
    services: 'Adeegyada',
    deliveryErrands: 'Geynta & Hawlaha',
    helpAtHome: 'Caawinta Guriga',
    pricing: 'Qiimaha',
    about: 'Nagu Saabsan',
    contact: 'Nala Soo Xiriir',
    book: 'Ballan Qabso',
    heroTitle: 'Caawintaada Maxalliga ah ee Göteborg',
    getStarted: 'Bilow',
    next: 'Xiga',
    sek: 'SEK',
    km: 'km'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('sv');
  const [isRTL, setIsRTL] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem('taskcham_language');
    if (saved) {
      setLanguage(saved);
      setIsRTL(saved === 'ar');
    } else {
      // Set default to Swedish if no saved preference
      localStorage.setItem('taskcham_language', 'sv');
    }
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    setIsRTL(lang === 'ar');
    localStorage.setItem('taskcham_language', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.sv[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'sv', name: 'Svenska', flag: '🇸🇪' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'sw', name: 'Kiswahili', flag: '🇰🇪' },
  { code: 'da', name: 'Dansk', flag: '🇩🇰' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'so', name: 'Soomaali', flag: '🇸🇴' }
];

// Backwards compatibility
export const languages = LANGUAGES;